import { GoogleGenAI } from "@google/genai";

const getClient = () => {
  const apiKey = process.env.API_KEY;
  if (!apiKey) throw new Error("API Key not found");
  return new GoogleGenAI({ apiKey });
};

export const generateTryOn = async (
  userImageBase64: string,
  clothingImageBase64OrUrl: string
): Promise<string> => {
  try {
    const ai = getClient();
    
    // We remove the data:image/xxx;base64, prefix if present for the API call
    const cleanUserImage = userImageBase64.split(',')[1] || userImageBase64;
    
    // Convert URL to base64 if needed (simplified for this demo: assuming clothing is a URL from our mock DB)
    // In a real scenario, we'd fetch the image blob and convert.
    // For this simulation, we will rely on Gemini's ability to understand the context or pass both as parts if possible.
    // Since `generateContent` with images requires inline data, we'll focus on the user image primarily 
    // and describe the clothing in text, or try to pass the clothing image if we had it as base64.
    
    // Let's assume for this mock service, we fetch the clothing image first if it's a URL
    let cleanClothingImage = clothingImageBase64OrUrl;
    if (clothingImageBase64OrUrl.startsWith('http')) {
        const response = await fetch(clothingImageBase64OrUrl);
        const blob = await response.blob();
        const reader = new FileReader();
        cleanClothingImage = await new Promise((resolve) => {
            reader.onloadend = () => {
                const res = reader.result as string;
                resolve(res.split(',')[1] || res);
            };
            reader.readAsDataURL(blob);
        });
    } else {
         cleanClothingImage = clothingImageBase64OrUrl.split(',')[1] || clothingImageBase64OrUrl;
    }

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image', // Using Flash Image for speed
      contents: {
        parts: [
          {
            text: "Perform a virtual try-on. I am providing an image of a person (first image) and an image of a clothing item (second image). Generate a high-quality, photorealistic image of the person wearing the clothing item. Preserve the person's pose, facial features, and background exactly. Fit the clothing naturally onto the body.",
          },
          {
            inlineData: {
              mimeType: 'image/jpeg',
              data: cleanUserImage,
            },
          },
           {
            inlineData: {
              mimeType: 'image/jpeg',
              data: cleanClothingImage,
            },
          },
        ],
      },
      config: {
        // We don't set responseMimeType for image models generally in this SDK version unless requesting JSON,
        // but here we expect text/image. The SDK handles the response.
        // We rely on the model returning an image part.
      }
    });

    // Check for image in response
    if (response.candidates && response.candidates[0].content.parts) {
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
           return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
      }
    }
    
    throw new Error("No image generated by AI.");

  } catch (error) {
    console.error("Gemini Try-On Error:", error);
    throw error;
  }
};
